Controllers/TerminalController.cs
using FirebirdSql.Data.FirebirdClient;
using ForeignKeyTunneling.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ForeignKeyTunneling.Controllers
{
    public class TerminalController : Controller
    {
        private readonly ILogger<TerminalController> _logger;
        private DB DB { get; init; }

        public TerminalController(DB db, ILogger<TerminalController> logger)
        {
            DB = db;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public string Execute(string command)
        {
            command = command.Trim(new char[] {' ', '\n'});
            string firstKeyword = command.Split(new char[] { ' ', ';', '\n' })[0].ToLower();
            string result = string.Empty;
            if (command.EndsWith(';'))
            {
                switch (firstKeyword)
                {
                    case "":
                        // No command to issue
                        break;
                    case "select":
                        using (FbConnection connection = DB.GetConnection())
                        {
                            result = DB.ExecuteSelect(command);
                        }
                        break;
                    default:
                        using (FbConnection connection = DB.GetConnection())
                        {
                            FbCommand dbCommand = connection.CreateCommand();
                            dbCommand.CommandText = command;
                            int numRows = dbCommand.ExecuteNonQuery();
                            result = $"Rows affected: {numRows}";
                        }
                        break;
                }
            }
            else
            {
                result = command;
            }
            return result;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForeignKeyTunneling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.12/themes/default/style.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/jquery.terminal@2.x.x/css/jquery.terminal.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ForeignKeyTunneling</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MetaData">DB MetaData</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Terminal" asp-action="Index">DB Terminal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous">
        </script>
        <script src="https://unpkg.com/jquery.terminal@2.x.x/js/jquery.terminal.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.12/jstree.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>